echo "`find /mnt/d/2012-10-06_Casamento -type f |wc -l` arquivos em D:\2012-10-06_Casamento"
echo "`find /mnt/e/2012-10-06_Casamento -type f |wc -l` arquivos em E:\2012-10-06_Casamento"
echo "==============================================="
echo "`find /mnt/d/BKP-FLASH-SYMC -type f |wc -l` arquivos em D:\BKP-FLASH-SYMC"
echo "`find /mnt/e/BKP-FLASH-SYMC -type f |wc -l` arquivos em E:\BKP-FLASH-SYMC"
echo "==============================================="
echo "`find /mnt/d/FOTOS-BRUNO -type f |wc -l` arquivos em D:\FOTOS-BRUNO"
echo "`find /mnt/e/FOTOS-BRUNO -type f |wc -l` arquivos em E:\FOTOS-BRUNO"
echo "==============================================="
echo "`find /mnt/d/FOTOS-CANON -type f |wc -l` arquivos em D:\FOTOS-CANON"
echo "`find /mnt/e/FOTOS-CANON -type f |wc -l` arquivos em E:\FOTOS-CANON"
echo "==============================================="
echo "`find /mnt/d/FOTOS-JULIANA -type f |wc -l` arquivos em D:\FOTOS-JULIANA"
echo "`find /mnt/e/FOTOS-JULIANA -type f |wc -l` arquivos em E:\FOTOS-JULIANA "
echo "==============================================="
echo "`find /mnt/d/MOVIES -type f |wc -l` arquivos em D:\MOVIES"
echo "`find /mnt/e/MOVIES -type f |wc -l` arquivos em E:\MOVIES"
echo "==============================================="
echo "`find /mnt/d/MUSICAS -type f |wc -l` arquivos em D:\MUSICAS "
echo "`find /mnt/e/MUSICAS -type f |wc -l` arquivos em E:\MUSICAS"
echo "==============================================="
echo "`find /mnt/d/OneDrive -type f |wc -l` arquivos em D:\OneDrive"
echo "`find /mnt/e/OneDrive -type f |wc -l` arquivos em E:\OneDrive "
echo "==============================================="
echo "`find /mnt/d/SOFTWARES -type f |wc -l` arquivos em D:\SOFTWARES"
echo "`find /mnt/e/SOFTWARES -type f |wc -l` arquivos em E:\SOFTWARES"
echo "==============================================="
